@hostname = localhost
@port = 8080
@host = http://{{hostname}}:{{port}}
@contentType = content-type: application/json

###----------------------
@r = restaurants
GET {{host}}/{{r}}
###
GET {{host}}/{{r}}/1
###
PUT {{host}}/{{r}}/1/active
###
DELETE {{host}}/{{r}}/1/active

###----------------------
@r = paymentmethods
GET {{host}}/{{r}}
###
GET {{host}}/{{r}}/7
###
POST {{host}}/{{r}}
{{contentType}}

{
    "description": "asd2"
}
###
DELETE {{host}}/{{r}}/6
###
PUT {{host}}/{{r}}/4
{{contentType}}

{
    "description": "asd"
}
