@hostname = localhost
@port = 8080
@host = http://{{hostname}}:{{port}}
@contentType = content-type: application/json
@r = cities

###----------------------
GET {{host}}/{{r}}
###
GET {{host}}/{{r}}/1
###
POST {{host}}/{{r}}
{{contentType}}

{
    "name": "Varginha",
    "state": {
        "id": 1
    }
}
###
PUT {{host}}/{{r}}/1
{{contentType}}

{
    "name": "Varginha",
    "state": {
        "id": 2
    }
}