@hostname = localhost
@port = 8080
@host = http://{{hostname}}:{{port}}
@contentType = content-type: application/json
@r = groups
@p = permissions

###----------------------
GET {{host}}/{{r}}
###
GET {{host}}/{{r}}/4
###
POST {{host}}/{{r}}
{{contentType}}

 {
    "name": "GERENTE",
    "description": "Gerente"
  }
###
PUT {{host}}/{{r}}/4
{{contentType}}

 {
    "name": "GERENTEAlterado",
    "description": "Gerente"
  }
###
DELETE {{host}}/{{r}}/4
### permissions
GET {{host}}/{{r}}/4/{{p}}
###
PUT {{host}}/{{r}}/2/{{p}}/2
###
DELETE {{host}}/{{r}}/2/{{p}}/2