@hostname = localhost
@port = 8080
@host = http://{{hostname}}:{{port}}
@contentType = content-type: application/json
@k = kitchens

###----------------------
GET {{host}}/{{k}}
###----------------------
GET {{host}}/{{k}}?size=2
###----------------------
GET {{host}}/{{k}}?size=2&page=1
###----------------------
GET {{host}}/{{k}}?size=2&page=0&sort=name,desc&sort=id
###
GET {{host}}/{{k}}/4
###