@hostname = localhost
@port = 8080
@host = http://{{hostname}}:{{port}}
@contentType = content-type: application/json
@r = restaurants

###----------------------
GET {{host}}/{{r}}
###
GET {{host}}/{{r}}/1
###
DELETE {{host}}/{{r}}/1/active
###
POST {{host}}/{{r}}
{{contentType}}

{
  "name": "Thai Gourmet",
  "shippingFee": 10.00,
  "kitchen": {
    "id": 1
  },
  "address": {
    "zipCode": "38400-999",
    "street": "Rua João Pinheiro",
    "number": "1000",
    "complement": null,
    "neighborhood": "Centro",
    "city": {
      "id": 100
    }
  }
}
###
PUT {{host}}/{{r}}/7
{{contentType}}

{
  "name": "Thai Gourmet",
  "shippingFee": 10.00,
  "kitchen": {
    "id": 1
  },
  "address": {
    "zipCode": "38400-999",
    "street": "Rua João Pinheiro",
    "number": "2000",
    "complement": null,
    "neighborhood": "Centro",
    "city": {
      "id": 100
    }
  }
}

