@hostname = localhost
@port = 8080
@host = http://{{hostname}}:{{port}}
@contentType = content-type: application/json
@accept = Accept: application/PDF,application/json
@s = statistics

###----------------------
GET {{host}}/{{s}}/daily-sales
{{accept}}
