@hostname = localhost
@port = 8080
@host = http://{{hostname}}:{{port}}
@contentType = content-type: application/json
@r = users
@g = groups

###----------------------
GET {{host}}/{{r}}
###
GET {{host}}/{{r}}/1
###
POST {{host}}/{{r}}
{{contentType}}

 {
    "name": "asasd",
    "email": "gerente@gerente.com",
    "password": "12345678"
  }
###
PUT {{host}}/{{r}}/4
{{contentType}}

 {
    "name": "nome alterado",
    "email": "gerente@gerenteAlterado.com"
  }
###
DELETE {{host}}/{{r}}/4
###
PUT {{host}}/{{r}}/1/password
{{contentType}}

{
    "oldPassword" : "",
    "newPassword" : ""
}
###
GET {{host}}/{{r}}/3/{{g}}
###
PUT {{host}}/{{r}}/3/{{g}}/1
###
DELETE {{host}}/{{r}}/3/{{g}}/1